name: deploy

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: yarn install
        run: yarn install --frozen-lockfile
        working-directory: ./website
      - name: install solc
        run: |
          # Install solc v0.4.24 manually onto Linux
          mkdir -p "$HOME/bin"
          curl -s -f -L "https://github.com/ethereum/solidity/releases/download/v0.4.24/solc-static-linux" -o "$HOME/bin/solc"
          chmod u+x "$HOME/bin/solc"
          echo "Installed solc-v0.4.24"
          export PATH=$HOME/bin:$PATH
          solc --version
      - name: build
        run: |
          export PATH=$HOME/bin:$PATH
          solc --version
          yarn run build
        working-directory: ./website
      - name: deploy
        run: |
          git config --global user.email "autobot@noreply.aragon.org"
          git config --global user.name "Autobots, roll out!"
          echo "machine github.com login arabot-1 password ${{ secrets.GIT_TOKEN }}" > $HOME/.netrc
          GIT_USER="arabot-1" npx docusaurus-publish
        working-directory: ./website
env:
  CI: true
